# Generated by Django 5.2.12 on 2026-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Client'), ('staff', 'Employé'), ('admin', 'Administrateur'), ('influencer', 'Influenceuse')], default='customer', max_length=20),
        ),
    ]
